### ISSUE TITLE
Estimating recombination rates between two populations

### ISSUE THREAD

**Issue by fpusan** [sid-krish/rhometa#54]
Hi there!
I would be interested in estimating the recombination rates between two populations of the same species. I would have the reference genome for the species and the fastq/BAM files for both sites.
Could I use rhometa to get an estimate of intra and inter-population recombination rates? If so, how?
Thanks in advance,
Fernando

**Comment by koadman** [comment]
Hi Fernando, one approach might be to run rhometa three times, once on each of the individual populations and once on the combined dataset. Before you do that on real data I think it would be wise to evaluate the strategy on a simulated dataset that is as close as possible to your real dataset in characteristics so that you can understand whether the method can produce the expected results even in the ideal setting of a simulation. If it works reasonably well on the simulation then it might be informative on real data, but if it doesn't work on simulated data then it seems very unlikely to produce meaningful results on a real dataset. Among other things I suggest you pay attention to the amount of data / number of reads from each population that are included in analysis.

**Comment by koadman** [comment]
@isidoramorel yes it should be possible to concatenate the reads. But if you've already mapped reads from each sample against the same reference, it might be faster/easier to just concatenate or merge the bamfiles with `samtools cat` or `samtools merge`, possibly after downsampling one or both of them. I'm not aware of any testing that's been done to validate this way of using rhometa, however. The coalescent with recombination model used in rhometa does not account for population structure, and it's not obvious (to me) what to expect when giving it data from a structured population (i.e. data mixed among two different populations).
